"""feeds_feedback_domain_policies

Revision ID: 2033895bcbc7
Revises: 7694bae5ddb2
Create Date: 2026-10-07 10:53:05.893681
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '2033895bcbc7'
down_revision: str | None = '7694bae5ddb2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_fetch_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('playwright_fallback', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rate_limit_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_fetch_policies')),
    sa.UniqueConstraint('domain', name=op.f('uq_domain_fetch_policies_domain'))
    )
    op.create_table('source_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_seconds', sa.Float(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_feeds')),
    sa.UniqueConstraint('url', name=op.f('uq_source_feeds_url'))
    )
    op.create_index(op.f('ix_source_feeds_kind'), 'source_feeds', ['kind'], unique=False)
    op.create_table('feed_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.String(length=1024), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_feed_entries_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feed_id'], ['source_feeds.id'], name=op.f('fk_feed_entries_feed_id_source_feeds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_entries')),
    sa.UniqueConstraint('feed_id', 'entry_id', name='uq_feed_entries_feed_entry_id')
    )
    op.create_index(op.f('ix_feed_entries_company_id'), 'feed_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_feed_entries_feed_id'), 'feed_entries', ['feed_id'], unique=False)
    op.create_table('operator_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('suggested_adjustment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_operator_feedback_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_operator_feedback_opportunity_id_opportunities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_feedback'))
    )
    op.create_index(op.f('ix_operator_feedback_company_id'), 'operator_feedback', ['company_id'], unique=False)
    op.create_index(op.f('ix_operator_feedback_opportunity_id'), 'operator_feedback', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_feedback_opportunity_id'), table_name='operator_feedback')
    op.drop_index(op.f('ix_operator_feedback_company_id'), table_name='operator_feedback')
    op.drop_table('operator_feedback')
    op.drop_index(op.f('ix_feed_entries_feed_id'), table_name='feed_entries')
    op.drop_index(op.f('ix_feed_entries_company_id'), table_name='feed_entries')
    op.drop_table('feed_entries')
    op.drop_index(op.f('ix_source_feeds_kind'), table_name='source_feeds')
    op.drop_table('source_feeds')
    op.drop_table('domain_fetch_policies')
    # ### end Alembic commands ###
