"""people_research_tasks_buyer_role

Revision ID: ffdb60115b4a
Revises: 4f78b5bf0ca6
Create Date: 2026-09-30 18:15:50.476502
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'ffdb60115b4a'
down_revision: str | None = '4f78b5bf0ca6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('public_profile_url', sa.String(length=2048), nullable=True),
    sa.Column('public_email', sa.String(length=320), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_people_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_people_source_snapshot_id_source_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people'))
    )
    op.create_index(op.f('ix_people_company_id'), 'people', ['company_id'], unique=False)
    op.create_index(op.f('ix_people_source_snapshot_id'), 'people', ['source_snapshot_id'], unique=False)
    op.create_table('research_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_research_tasks_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_research_tasks_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_tasks'))
    )
    op.create_index(op.f('ix_research_tasks_company_id'), 'research_tasks', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_opportunity_id'), 'research_tasks', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_research_tasks_status'), 'research_tasks', ['status'], unique=False)
    op.add_column('opportunities', sa.Column('buyer_role_rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'buyer_role_rationale')
    op.drop_index(op.f('ix_research_tasks_status'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_opportunity_id'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_company_id'), table_name='research_tasks')
    op.drop_table('research_tasks')
    op.drop_index(op.f('ix_people_source_snapshot_id'), table_name='people')
    op.drop_index(op.f('ix_people_company_id'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
