"""scoring_fields

Revision ID: 4f78b5bf0ca6
Revises: 2007bad956ef
Create Date: 2026-09-30 18:07:07.306420
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '4f78b5bf0ca6'
down_revision: str | None = '2007bad956ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('icp_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('exclusion_reason', sa.Text(), nullable=True))
    op.add_column('opportunities', sa.Column('score_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('opportunities', sa.Column('promotion_blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('opportunities', sa.Column('outreach_ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opportunities', sa.Column('outreach_ready_override', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('opportunities', sa.Column('outreach_ready_override_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'outreach_ready_override_reason')
    op.drop_column('opportunities', 'outreach_ready_override')
    op.drop_column('opportunities', 'outreach_ready_at')
    op.drop_column('opportunities', 'promotion_blockers')
    op.drop_column('opportunities', 'score_reasons_json')
    op.drop_column('companies', 'exclusion_reason')
    op.drop_column('companies', 'icp_reasons_json')
    # ### end Alembic commands ###
