"""outreach_tasks_and_interactions

Revision ID: 4243a9b09e7f
Revises: ffdb60115b4a
Create Date: 2026-10-01 11:14:27.577364
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '4243a9b09e7f'
down_revision: str | None = 'ffdb60115b4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('brief_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_outreach_tasks_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_outreach_tasks_person_id_people'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_tasks'))
    )
    op.create_index(op.f('ix_outreach_tasks_due_at'), 'outreach_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_outreach_tasks_opportunity_id'), 'outreach_tasks', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_outreach_tasks_person_id'), 'outreach_tasks', ['person_id'], unique=False)
    op.create_index(op.f('ix_outreach_tasks_status'), 'outreach_tasks', ['status'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('outreach_task_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_interactions_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outreach_task_id'], ['outreach_tasks.id'], name=op.f('fk_interactions_outreach_task_id_outreach_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_interactions_person_id_people'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    op.create_index(op.f('ix_interactions_next_action_at'), 'interactions', ['next_action_at'], unique=False)
    op.create_index(op.f('ix_interactions_opportunity_id'), 'interactions', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_interactions_outreach_task_id'), 'interactions', ['outreach_task_id'], unique=False)
    op.create_index(op.f('ix_interactions_person_id'), 'interactions', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactions_person_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_outreach_task_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_opportunity_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_next_action_at'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_outreach_tasks_status'), table_name='outreach_tasks')
    op.drop_index(op.f('ix_outreach_tasks_person_id'), table_name='outreach_tasks')
    op.drop_index(op.f('ix_outreach_tasks_opportunity_id'), table_name='outreach_tasks')
    op.drop_index(op.f('ix_outreach_tasks_due_at'), table_name='outreach_tasks')
    op.drop_table('outreach_tasks')
    # ### end Alembic commands ###
