"""signals_and_opportunities

Revision ID: 2007bad956ef
Revises: ded76058b364
Create Date: 2026-09-30 17:51:50.510343
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = '2007bad956ef'
down_revision: str | None = 'ded76058b364'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('solution_family', sa.String(length=64), nullable=False),
    sa.Column('problem_or_change', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('business_outcome', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=False),
    sa.Column('buyer_role', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('unknowns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggering_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_opportunities_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggering_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_opportunities_triggering_snapshot_id_source_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_triggering_snapshot_id'), 'opportunities', ['triggering_snapshot_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_excerpt', sa.Text(), nullable=False),
    sa.Column('strength', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_signals_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_signals_source_snapshot_id_source_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_signals_source_snapshot_id'), 'signals', ['source_snapshot_id'], unique=False)
    op.create_index(op.f('ix_signals_type'), 'signals', ['type'], unique=False)
    op.create_table('opportunity_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_evidence_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_opportunity_evidence_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_opportunity_evidence_source_snapshot_id_source_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_evidence')),
    sa.UniqueConstraint('opportunity_id', 'signal_id', name='uq_opportunity_evidence_opportunity_signal')
    )
    op.create_index(op.f('ix_opportunity_evidence_opportunity_id'), 'opportunity_evidence', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_evidence_signal_id'), 'opportunity_evidence', ['signal_id'], unique=False)
    op.create_index(op.f('ix_opportunity_evidence_source_snapshot_id'), 'opportunity_evidence', ['source_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_evidence_source_snapshot_id'), table_name='opportunity_evidence')
    op.drop_index(op.f('ix_opportunity_evidence_signal_id'), table_name='opportunity_evidence')
    op.drop_index(op.f('ix_opportunity_evidence_opportunity_id'), table_name='opportunity_evidence')
    op.drop_table('opportunity_evidence')
    op.drop_index(op.f('ix_signals_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_snapshot_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_opportunities_triggering_snapshot_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company_id'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
