"""llm_calls_and_company_facts

Revision ID: ded76058b364
Revises: fd603e22187f
Create Date: 2026-09-30 17:23:54.876660
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = 'ded76058b364'
down_revision: str | None = 'fd603e22187f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_llm_calls_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['source_snapshots.id'], name=op.f('fk_llm_calls_source_snapshot_id_source_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    op.create_index(op.f('ix_llm_calls_company_id'), 'llm_calls', ['company_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_source_snapshot_id'), 'llm_calls', ['source_snapshot_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_task'), 'llm_calls', ['task'], unique=False)
    op.add_column('companies', sa.Column('facts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('facts_snapshot_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('facts_extracted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_companies_facts_snapshot_id'), 'companies', ['facts_snapshot_id'], unique=False)
    op.create_foreign_key('fk_companies_facts_snapshot_id', 'companies', 'source_snapshots', ['facts_snapshot_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_companies_facts_snapshot_id', 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_facts_snapshot_id'), table_name='companies')
    op.drop_column('companies', 'facts_extracted_at')
    op.drop_column('companies', 'facts_snapshot_id')
    op.drop_column('companies', 'facts_json')
    op.drop_index(op.f('ix_llm_calls_task'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_source_snapshot_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_company_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
